### ISSUE TITLE
Bug use zoomist with modal bootstrap

### ISSUE THREAD

**Issue by Zecrum** [cotton123236/zoomist#12]
Hello, I have a bug when I use zoomist in a modal box created with bootstrap.
The image does not appear.

link jsfiddle : https://jsfiddle.net/kjuL1375/11/

Can you help me ?

Thanks you
Alexandre

**Comment by cotton123236** [comment]
Hello @Zecrum 

That is because you use `show.bs.modal` event for your example.
According to bootstrap docs `show.bs.modal` event fires immediately when the show instance method is called, so zoomist will get the wrong width and height data.
You should use `shown.bs.modal` event for you modal.

And this is the recommend usage below

`
let isOpened = false
const zoomist = new Zoomist('#zoomImage', {
  height: '90%',
  slider: true,
  zoomer: true
})

const exampleModal = document.getElementById('exampleModal')
exampleModal.addEventListener('shown.bs.modal', event => {
	if (isOpened) return
	zoomist.update()
	isOpened = true
})
`

Let me know if it's still not working.
Thank you!

**Comment by Zecrum** [comment]
Hello, 

It's work.

Thanks you and have a nice day !
