### ISSUE TITLE
why can't I click on the button inside the zoomist-image container?

### ISSUE THREAD

**Issue by ukizet** [cotton123236/zoomist#38]
@cotton123236 why can't I click on the button inside the zoomist-image container? I tried clicking on the button inside the zoomist-wrapper container and it works, but then I can't zoom into button. What can I do to be able to both zoom in and click on the button?

[Codesandbox example](https://codesandbox.io/s/unruffled-kirch-47q29w?file=/src/index.ts)

_Originally posted by @ukizet in https://github.com/cotton123236/zoomist/issues/33#issuecomment-1837603432_

Sry for another created issue but i really wanna use zoomist in my project.

**Comment by cotton123236** [comment]
HEY @ukizet ,
That is because `.zoomist-image` is set to `pointer-events: none;` to prevent some events on dragging (like clicking `<a></a>` tag on dragging).
You can add `.zoomist-container .zoomist-image { pointer-events: auto; }` in your css file to make those buttons works, but it may cause some effects while dragging.

**Comment by ukizet** [comment]
@cotton123236 ty for response.
